function FigureTitle(title_string,font_size)
if nargin < 2
    font_size = 12;
end

annotation('textbox', [0 0.80 1 0.20], ...
            'String', (title_string), ...
            'FontSize',font_size,...
            'EdgeColor', 'none', ...
            'Interpreter','none',...
            'HorizontalAlignment', 'center')