function bits = BDM_bits

bits = {'Trial_Onset', 'Fix_cross', 'Fractal_disp', 'Bid_start',...
    'Bid_stable', 'Win_Lose', 'Reward_epoch_end', 'Budget_epoch_end',...
    'Free_reward', 'Reward_tap', 'Budget_tap', '3rd_tap', 'Trial_end','Error'};