---
title: "Untitled"
author: "Robert Hickman"
date: "11/11/2020"
output: html_document
---

```{r}
library(tidyverse)
library(ggplot2)
```

```{r}
df <- data.frame(
  x = rep(seq(0, 10, by = 0.1), 4),
  u = rep(1:4, each = 101)
) %>%
  mutate(y = ((1/(x+3) * 20) - 1.5) * 3) %>%
  mutate(x2 = x + (u * 2) - 5)

points <- data.frame(
  x = c(1, 5),
  y = c(4, 1),
  u = 1
)

labels <- data.frame(
  x = c(9,7),
  y = c(4,8),
  a = c(0, -60),
  label = c("different\nutilities", "same utility")
)

arrows <- data.frame(
  x = c(5.75, 6.5, 7.25),
  y = c(8.5, 7, 5.5)
)
arrows2 <- data.frame(
  x = c(8.5, 9, 9.25),
  xend = c(5.25, 7, 9),
  y = c(3.25, 3.25, 3.25)
)

p <- ggplot(df) +
  geom_line(size = 2, aes(x = x2, y = y, colour = factor(u), group = u)) +
  geom_segment(data = points, aes(x = 0, xend = x, y = y, yend = y), colour = "black", linetype = "dashed", size = 2) +
  geom_segment(data = points, aes(x = x, xend = x, y = y, yend = 0), colour = "black", linetype = "dashed", size = 2) +
  geom_point(data = points, aes(x = x, y = y), fill = "dodgerblue", size = 7, shape = 21, colour = "black", stroke = 3) +
  geom_text(data = labels, aes(x = x, y = y, angle = a, label = label), size = 10) +
  geom_segment(data = arrows, aes(x = x, xend = x - 1, y = y + 1, yend = y), arrow = arrow(length = unit(0.03, "npc")), size = 3) +
  geom_segment(data = arrows2, aes(x = x, xend = xend, y = y, yend = y - 2), arrow = arrow(length = unit(0.03, "npc")), size = 3) +
  scale_colour_viridis_d(option = "plasma", name = "utility along\ncurve (utils)") +
  scale_x_continuous(limits = c(0, 10), breaks = seq(0, 10, 2)) +
  scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, 2)) +
  labs(
    x = "quantity of good 1",
    y = "quantity of good 2"
  ) +
  theme_minimal() +
  theme(
  axis.text = element_text(size = 16),
  axis.title = element_text(size = 18),
    legend.key.size = unit(0.4, "cm"), 
    legend.title = element_text(size = 16),
    legend.text = element_text(size = 12)
)

```

