function cb = ModigRandSeq
% A code to generate random sequence
% Policy of how to make a random sequence is based on RandTbl.mat
% Generated sequence is placed under the structure Tbl.Rand by the name of the
% rand_'seq_name' defined in the RandTbl.mat
%
% coded by skoba (skoba-tky@umin.ac.jp) 27 June 2005
% last modified by skoba 27 June 2005
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
global Tbl TaskOp Stim
cb = 1;
if isfield(Tbl,'Rand')
    rand_items = Tbl.RandTbl(:,Tbl.RandTblColumnID.rand_seq_name);
    
    for rr = 1:length(rand_items)
        rand_item = eval(strcat('Tbl.Rand.',cell2mat(rand_items(rr))));
        if isfield(rand_item,'link')
           for ll = 1: length(rand_item.link)
               link_stim = rand_item.link(ll).stim;
               link_policy = rand_item.link(ll).policy;
               if eval(strcat('isfield(Stim.',link_stim,',','''','CurSet','''',')'))
                   switch link_policy
                       case 'image_policy'
                           eval(strcat('rand_item.num_member = length(Stim.',link_stim,'.CurSet.image_selection);'));
                       case 'position_policy'
                           eval(strcat('rand_item.num_member = length(Stim.',link_stim,'.CurSet.position_selection);'));
                       case 'color_policy'
                           eval(strcat('rand_item.num_member = length(Stim.',link_stim,'.CurSet.color_selection);'));
                       case 'size_policy'
                           eval(strcat('rand_item.num_member = length(Stim.',link_stim,'.CurSet.size_selection);'));
                   end
               else
                    % output warning in the main menu in the future
               end
           end
        end
        switch lower(rand_item.rand_method)
            case 'pseudorand'
                final_seq = [];
                for ss = 1: ceil(TaskOp.count.total_seq / rand_item.num_member)
                    temp_seq = 1:1:rand_item.num_member; % pseudorandom sequence before shuffling (1,2,3,...)
                    seq_ok = 0;
                    num_shuffle = 0; % set this to avoid endless shuffling
                    if rand_item.num_member == 1
                        rand_item.max_reps = 1;
                    end
                    if rand_item.max_reps>=2,
                        while seq_ok == 0 & num_shuffle <10 % make shuffle until number of repeated trials get less than request.
                            temp_seq = Shuffle(temp_seq);
                            rep_seq = findreps([final_seq temp_seq],rand_item.max_reps);
                            if isempty(rep_seq)
                                final_seq = [final_seq temp_seq];
                                seq_ok =1;
                                num_shuffle = num_shuffle +1;
                            end
                        end
                    else
                        final_seq = [final_seq temp_seq];
                    end
                end
            case 'sequential'
                final_seq = mod(0:TaskOp.count.total_seq-1,rand_item.num_member)+1;
            case 'randsample' % randome sequence generated by matlab function. Make best effort to reduce number of repeated trials, if requested, but not garanteed.
                seq_ok = 0;
                num_shuffle = 0;
                if rand_item.max_reps>=2,
                    while seq_ok == 0 & num_shuffle <20
                        final_seq = RandSample([1:1:rand_item.num_member],[1 TaskOp.count.total_seq]);
                        rep_seq = findreps(final_seq,rand_item.max_reps);
                        if isempty(rep_seq)
                            seq_ok = 1;
                        end
                        num_shuffle = num_shuffle + 1;
                    end
                else
                    str = strcat('Parameter max_reps in RandTbl.mat for item: ', cell2mat(rand_items(rr)),' is smaller than 3. This is not acceptable.');
                    fprintf(str);
                    final_seq = RandSample([1:1:rand_item.num_member],[1 TaskOp.count.total_seq]); % requirment for max_reps is ignored because the value is too small. Show warning.
                end
        end
        final_seq = final_seq(1:TaskOp.count.total_seq);
        eval(strcat('Tbl.Rand.',cell2mat(rand_items(rr)),'.seq = final_seq;'));
        y = checkreps(final_seq);
        cur_max_reps = max(y.reps);
        eval(strcat('Tbl.Rand.',cell2mat(rand_items(rr)),'.cur_max_reps = cur_max_reps;'));
    end
    ModigMessage('m&c','sequence randomized',5);
else
    cb = 0;
end

