---
title: "juice response"
author: "Robert Hickman"
date: "2025-03-12"
output: html_document
---

```{r setup, warning=FALSE,message=FALSE}
rm(list = ls())
set.seed(3459)
setwd("~/projects/thesis_scripts/figure_scripts/juice_pay/")
library(tidyverse)
library(jsonlite)
library(patchwork)
library(svglite)
library(viridis)
library(colorspace)
library(broom)

source("../../src/neuron_smoothing.R")
source("../../src/figs.R")

monkey_fill_pal <- scale_fill_manual(values = c("royalblue", "darkorange"), labels = c("Monkey U", "Monkey V"), guide = FALSE)
monkey_col_pal <- scale_colour_manual(values = c("royalblue", "darkorange"), labels = c("Monkey U", "Monkey V"), guide = FALSE)

neuronal_data <- bind_rows(
  readRDS("../../data/neurons/onefrac_noerror_neuronal_data.rds"),
  readRDS("../../data/neurons/threefrac_noerror_neuronal_data.rds"),
)
task_data <- readRDS("../../data/neurons/task_data.rds")

cell_baselines_fractals <-
  readRDS("../../data/baseline/cell_prefc_baselines_fractals_smoothed.rds")
cell_baselines_fractal_counts <-
  readRDS("../../data/baseline/cell_prefc_baselines_fractals.rds")
cell_baselines_counts <-
  readRDS("../../data/baseline/cell_prefc_baselines.rds")

sigcells_uly <-
  read_csv("../../data/cells/uly_sig_cells.csv") %>%
  mutate(monkey = "Monkey U") %>%
  mutate(date = as.Date(date, "%d-%b-%y"))
sigcells_vice <-
  read_csv("../../data/cells/vice_sig_cells.csv") %>%
  mutate(monkey = "Monkey V") %>%
  mutate(date = as.Date(date, "%d-%b-%Y"))

sigcells <-
  bind_rows(sigcells_uly, sigcells_vice) %>%
  mutate(cell = paste0("cell", gsub("^(Clust)([0-9])(_.*)$", "\\2", cluster)))

monkey_windows <- read_csv("../../data/config/monkey_windows.csv")
configs <- read_csv("../../data/config/configs.csv")

group_cols <- c("date", "monkey", "cell")
group_cols_fractal <- c(group_cols, "fractal_value")

juice_sig_cells <- read_csv("./juice_pay_sig_cells.csv")

relevant_cells <- sigcells %>%
  select(date, monkey, cell, isDA, isResponsive, numTrGood, DAFracResponsive, DABidResponsive, DAWinloseResponsive) %>%
  filter(isDA == 1 & isResponsive == 1 & numTrGood == 1) %>%
  distinct(date, monkey, cell, .keep_all = TRUE) %>%
  inner_join(juice_sig_cells)

n_start <- filter(configs, var == "neurons_start") %>% pull(value)
n_end <- filter(configs, var == "neurons_end") %>% pull(value)
smooth_window <-
  filter(configs, var == "smooth_window") %>% pull(value)
```

```{r juice spikes}
pre_start <- -400
pre_end <- -50

ntiles <- 25

juice_task_data <- task_data %>%
  filter(situation %in% c(1,2,3)) %>%
  filter(map_lgl(error_bit, ~ is.na(unlist(.x)))) %>%
  select(date, monkey, trial, fractal_value, monkey_bid, computer_bid) %>%
  distinct(date, monkey, trial, .keep_all = TRUE) %>%
  filter(monkey_bid != computer_bid) %>%
  mutate(
    monkey_win = monkey_bid > computer_bid,
    monkey_bid_ntile = cut(
      monkey_bid,
      breaks = seq(0, 100, by = 100/ntiles),
      labels = FALSE,
      include.lowest = TRUE
    )
  ) %>%
  group_by(monkey, monkey_bid_ntile, monkey_win) %>%
  filter(n() > 100)

juice_data <- neuronal_data %>%
  filter(situation %in% c(1,2,3)) %>%
  filter(map_lgl(bits, function(x) {
    if (!is.null(x) && is.data.frame(x) && nrow(x) > 0) {
      matching_rows <- x$names == "reward_epoch_end" & x$index == "upat"
      sum(matching_rows) == 1 && !is.na(x$vals[matching_rows])
    } else {
      FALSE
    }
  }))  %>%
  unnest(bits) %>%
  filter(names == "reward_epoch_end" & index == "upat") %>%
  pivot_wider(names_from = names, values_from = vals)

juice_spikes <- juice_data %>%
  inner_join(juice_task_data, by = c("date", "monkey", "trial")) %>%
  unnest(sorted_spikes) %>%
  mutate(spike_bit_time_ms = trial_spike_time_ms - reward_epoch_end) %>%
  group_by(date, monkey, trial, cell, monkey_win) %>%
  mutate(
    pre_spikes_count = sum(spike_bit_time_ms >= -1000 & spike_bit_time_ms <= 0)
  ) %>%
  ungroup() %>%
  filter(
    !(monkey == "Monkey V" &
      monkey_win == TRUE &
      round(spike_bit_time_ms) %in% c(72:75, 228:233, 386:389))
  ) %>%
  select(date, monkey, trial, cell, spike_bit_time_ms, fractal_value, monkey_win, pre_spikes_count, monkey_bid_ntile)%>%
  inner_join(juice_sig_cells)

```


```{r linear_model, warning=FALSE,message=FALSE}
ntiles = 25

winlose_task_data <- task_data %>%
  filter(situation %in% c(1, 2, 3)) %>%
  filter(monkey_bid != 0 & monkey_bid != 100) %>%
  select(date, monkey, session, trial, fractal_value, monkey_bid, computer_bid) %>%
  mutate(
    monkey_win = monkey_bid > computer_bid,
    monkey_bid_ntile = cut(
      monkey_bid,
      breaks = seq(0, 100, by = 100/ntiles),
      labels = FALSE,
      include.lowest = TRUE
    )
  ) %>%
  group_by(monkey, monkey_win, monkey_bid_ntile) %>%
  filter(n() > 15)

relevant_cells_ntiles <- merge(
  juice_sig_cells,
  winlose_task_data %>% select(monkey, monkey_win, monkey_bid_ntile) %>% distinct(),
  by = "monkey",
  all = TRUE
)

wl_spike_data <- neuronal_data %>%
  filter(situation %in% c(1,2,3)) %>%
  filter(map_lgl(bits, function(x) {
    if (!is.null(x) && is.data.frame(x) && nrow(x) > 0) {
      matching_rows <- x$names == "reward_epoch_end" & x$index == "upat"
      sum(matching_rows) == 1 && !is.na(x$vals[matching_rows])
    } else {
      FALSE
    }
  }))  %>%
  unnest(bits) %>%
  filter(names == "reward_epoch_end" & index == "upat")

wl_spikes <- wl_spike_data %>%
  inner_join(winlose_task_data, by = c("date", "monkey", "session", "trial")) %>%
  select(date, monkey, session, trial, monkey_win, monkey_bid_ntile, wl_time = vals, sorted_spikes) %>%
  unnest(sorted_spikes) %>%
  mutate(spike_bit_time_ms = trial_spike_time_ms - wl_time) 

wl_spikes_ntiles <- wl_spikes %>%
  group_by(date, monkey, cell, session, trial, monkey_win, monkey_bid_ntile) %>%
  summarise(n = sum(spike_bit_time_ms >= 0 & spike_bit_time_ms <= 500), .groups = "drop") %>%
  right_join(relevant_cells_ntiles, by = c(group_cols, "monkey_win", "monkey_bid_ntile")) %>%
  mutate(n = replace_na(n ,0)) 

baselines <- cell_baselines_counts %>%
  inner_join(relevant_cells, by = group_cols) %>%
  group_by(date, monkey, cell, trial) %>%
  summarise(n = sum(spike_bit_time_ms >= -500 & spike_bit_time_ms <= 0), .groups = "drop") %>%
  mutate(adj_n = n) %>%
  group_by(date, monkey, cell) %>%
  summarise(mean_n = mean(adj_n), sd_n = sd(adj_n), .groups = "drop") %>%
  filter(sd_n != 0)

wl_normalised_spikes <- wl_spikes_ntiles %>%
  left_join(baselines, by = group_cols) %>%
  drop_na() %>%
  mutate(norm_n = (n - mean_n) / sd_n) %>%
  group_by(monkey, monkey_win, monkey_bid_ntile) %>%
  summarise(mean_n_s = mean(norm_n), sem = sd(norm_n) / sqrt(n()), .groups = "drop") %>%
  mutate(monkey_bid_perc = monkey_bid_ntile / ntiles) %>%
  filter(!is.na(sem))

p_win_norm_regression <- ggplot(wl_normalised_spikes %>% filter(monkey_win), aes(x = monkey_bid_perc, y = mean_n_s, colour = monkey, group = monkey)) + 
  stat_smooth(method = "lm") +
  geom_point(size = 2) + 
  geom_errorbar(aes(ymin = mean_n_s - sem, ymax = mean_n_s + sem), width = 0) +
  monkey_col_pal +
  labs(
    x = "monkey bid percentage",
    y = "normalised firing rate (impulses/s)"
  ) +
  theme_minimal() +
  facet_wrap(~ monkey, scales = "free_y") +
  theme(
    strip.background = element_blank(),
    strip.text = element_blank(),
    legend.position = "bottom"
  )

p_lose_norm_regression <- ggplot(wl_normalised_spikes %>% filter(!monkey_win), aes(x = monkey_bid_perc, y = mean_n_s, colour = monkey, group = monkey)) + 
  stat_smooth(method = "lm") +
  geom_point(size = 2) + 
  geom_errorbar(aes(ymin = mean_n_s - sem, ymax = mean_n_s + sem), width = 0) +
  monkey_col_pal +
  labs(
    x = "monkey bid percentage",
    y = "normalised firing rate (impulses/s)"
  ) +
  theme_minimal() +
  facet_wrap(~ monkey, scales = "free_y") +
  theme(
    strip.background = element_blank(),
    strip.text = element_blank(),
    legend.position = "bottom"
  )

```

```{r stats}
# Split data by monkey and monkey_win
monkey_u_win <- wl_normalised_spikes %>% 
  filter(monkey == "Monkey U", monkey_win == TRUE)

monkey_u_lose <- wl_normalised_spikes %>% 
  filter(monkey == "Monkey U", monkey_win == FALSE)

monkey_v_win <- wl_normalised_spikes %>% 
  filter(monkey == "Monkey V", monkey_win == TRUE)

monkey_v_lose <- wl_normalised_spikes %>% 
  filter(monkey == "Monkey V", monkey_win == FALSE)

# Run linear models for each group
model_u_win <- lm(mean_n_s ~ monkey_bid_perc, data = monkey_u_win)
model_u_lose <- lm(mean_n_s ~ monkey_bid_perc, data = monkey_u_lose)
model_v_win <- lm(mean_n_s ~ monkey_bid_perc, data = monkey_v_win)
model_v_lose <- lm(mean_n_s ~ monkey_bid_perc, data = monkey_v_lose)

# Get coefficient statistics and model fit metrics
coef_u_win <- tidy(model_u_win)
coef_u_lose <- tidy(model_u_lose)
coef_v_win <- tidy(model_v_win)
coef_v_lose <- tidy(model_v_lose)

glance_u_win <- glance(model_u_win)
glance_u_lose <- glance(model_u_lose)
glance_v_win <- glance(model_v_lose)
glance_v_lose <- glance(model_v_lose)

# Function to format estimate ± std.error
format_estimate <- function(estimate, std.error, digits = 4) {
  sprintf("%.4f ± %.4f", estimate, std.error)
}

# Create comprehensive results table
results_table <- bind_rows(
  data.frame(
    monkey = "Monkey U",
    outcome = "Win",
    intercept = format_estimate(
      coef_u_win$estimate[coef_u_win$term == "(Intercept)"],
      coef_u_win$std.error[coef_u_win$term == "(Intercept)"]
    ),
    slope = format_estimate(
      coef_u_win$estimate[coef_u_win$term == "monkey_bid_perc"],
      coef_u_win$std.error[coef_u_win$term == "monkey_bid_perc"]
    ),
    slope_p = coef_u_win$p.value[coef_u_win$term == "monkey_bid_perc"],
    adj_r_squared = glance_u_win$adj.r.squared
  ),
  data.frame(
    monkey = "Monkey U",
    outcome = "Lose",
    intercept = format_estimate(
      coef_u_lose$estimate[coef_u_lose$term == "(Intercept)"],
      coef_u_lose$std.error[coef_u_lose$term == "(Intercept)"]
    ),
    slope = format_estimate(
      coef_u_lose$estimate[coef_u_lose$term == "monkey_bid_perc"],
      coef_u_lose$std.error[coef_u_lose$term == "monkey_bid_perc"]
    ),
    slope_p = coef_u_lose$p.value[coef_u_lose$term == "monkey_bid_perc"],
    adj_r_squared = glance_u_lose$adj.r.squared
  ),
  data.frame(
    monkey = "Monkey Y",
    outcome = "Win",
    intercept = format_estimate(
      coef_v_win$estimate[coef_v_win$term == "(Intercept)"],
      coef_v_win$std.error[coef_v_win$term == "(Intercept)"]
    ),
    slope = format_estimate(
      coef_v_win$estimate[coef_v_win$term == "monkey_bid_perc"],
      coef_v_win$std.error[coef_v_win$term == "monkey_bid_perc"]
    ),
    slope_p = coef_v_win$p.value[coef_v_win$term == "monkey_bid_perc"],
    adj_r_squared = glance_v_win$adj.r.squared
  ),
  data.frame(
    monkey = "Monkey V",
    outcome = "Lose",
    intercept = format_estimate(
      coef_v_lose$estimate[coef_v_lose$term == "(Intercept)"],
      coef_v_lose$std.error[coef_v_lose$term == "(Intercept)"]
    ),
    slope = format_estimate(
      coef_v_lose$estimate[coef_v_lose$term == "monkey_bid_perc"],
      coef_v_lose$std.error[coef_v_lose$term == "monkey_bid_perc"]
    ),
    slope_p = coef_v_lose$p.value[coef_v_lose$term == "monkey_bid_perc"],
    adj_r_squared = glance_v_lose$adj.r.squared
  )
)

print(results_table)
```

```{r}
sig_cells_string <- paste0(
  "Monkey U: ",
  as.numeric(table(juice_sig_cells$monkey)["Monkey U"]),
  " putative dopamine neurons; ",
  "Monkey V: ",
  as.numeric(table(juice_sig_cells$monkey)["Monkey V"]),
  " putative dopamine neurons"
)

p_regression <-
  (
    p_win_norm_regression + theme(
      legend.position = "none",
      axis.text.x = element_blank(),
      axis.title.x = element_blank()
    )
  ) / p_lose_norm_regression + plot_annotation(title = '',
                                               subtitle = sig_cells_string,
                                               tag_levels = "A")

```

```{r eval = FALSE}
ggsave(
  file.path("./output", "profit_regression_fig.png"), 
  p_regression,
  width = 6.71,
  height = 7.5,
  dpi = 300,
  units = "in"
)

ggsave(
  file.path("./output", "profit_regression_fig.svg"), 
  p_regression,
  width = 6.71,
  height = 7.5,
  units = "in"
)

```

